### PR TITLE
Testing of issues 17 and 9

### PR DESCRIPTION
**Pull request by parvit**
This PR includes changes for issues #17 and #9, please refer to the respective tickets for explanations on those.

### CODE REVIEW

**Comment by parvit** [comment]
[qpep_anyconnect.zip](https://github.com/Project-Faster/qpep/files/10170661/qpep_anyconnect.zip)

Hi, find attached the prebuilt binaries for linux and windows with the latest changes in the branch that allow interoperability with AnyConnect vpn.

Be sure to use gateway port 1445 in tests.

**Comment by bizzbyster** [comment]
@parvit I'm ready to test. It has been a while since I have installed the quic_go client on my Windows machine. Are the README instructions up-to-date? I'm hoping to avoid lots of back and forths with you on my configuration.

**Comment by parvit** [comment]
@bizzbyster There has not been any change to the configuration for client or server, from the user point of view it should work the same as before.

**Comment by parvit** [comment]
Tested with @mfoxworthy, only issue remaining is that it does not currently work if user is in a domain because of restrictions in setting the proxy.
Will be investigated further in PR #36.

**Pull request merged**
